### ISSUE TITLE
Colonist.io

### ISSUE THREAD

**Issue by goktugyil** [minimuscle/colonist.io-electron#2]
Hey dev of colonist here. Thanks for making this. A while ago you wanted to contribute to Colonist. We didn’t have anything going back then, but we started accepting contributors. You can apply to become one in here: https://colonist.io/contribute.html

We’re also looking for full-time team members. Would you be interested in this? Do you know anyone who might be a good fit? 
https://blog.colonist.io/colonist-is-hiring/

**Comment by Esqarrouth** [comment]
Hey @minimuscle why did you decide to close the issue now

**Comment by minimuscle** [comment]
@goktugyil I have been updating this application to actually be downloadable and run! As this issue was 1.5 years old I didn't think it was relevant anymore.

**Comment by Esqarrouth** [comment]
Is this posted somewhere? Getting installs?

**Comment by minimuscle** [comment]
Under releases. Just runs a frameless fullscreen chromium. Only just posted it 12 hours ago.

**Comment by Esqarrouth** [comment]
Got it

> We’re also looking for full-time team members. Would you be interested in this? Do you know anyone who might be a good fit?
> https://blog.colonist.io/colonist-is-hiring/

Have you checked this?
